import { MigrationInterface, QueryRunner } from "typeorm";

export class AddMediaItem1773652173397 implements MigrationInterface {
    name = 'AddMediaItem1773652173397'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "app_account_preferences" DROP CONSTRAINT "FK_account_preferences_account"`);
        await queryRunner.query(`ALTER TABLE "app_habit_entry" DROP CONSTRAINT "FK_app_habit_entry_account"`);
        await queryRunner.query(`ALTER TABLE "app_habit_entry" DROP CONSTRAINT "FK_app_habit_entry_habit"`);
        await queryRunner.query(`ALTER TABLE "app_habit" DROP CONSTRAINT "FK_app_habit_account"`);
        await queryRunner.query(`ALTER TABLE "app_finance_wallets" DROP CONSTRAINT "FK_app_finance_wallets_account"`);
        await queryRunner.query(`ALTER TABLE "app_finance_categories" DROP CONSTRAINT "FK_app_finance_categories_account"`);
        await queryRunner.query(`ALTER TABLE "app_finance_categories" DROP CONSTRAINT "FK_app_finance_categories_parent"`);
        await queryRunner.query(`ALTER TABLE "app_finance_subscriptions" DROP CONSTRAINT "FK_app_finance_subscriptions_account"`);
        await queryRunner.query(`ALTER TABLE "app_finance_subscriptions" DROP CONSTRAINT "FK_app_finance_subscriptions_wallet"`);
        await queryRunner.query(`ALTER TABLE "app_finance_subscriptions" DROP CONSTRAINT "FK_app_finance_subscriptions_category"`);
        await queryRunner.query(`ALTER TABLE "app_finance_transactions" DROP CONSTRAINT "FK_app_finance_transactions_account"`);
        await queryRunner.query(`ALTER TABLE "app_finance_transactions" DROP CONSTRAINT "FK_app_finance_transactions_category"`);
        await queryRunner.query(`ALTER TABLE "app_finance_transactions" DROP CONSTRAINT "FK_app_finance_transactions_wallet"`);
        await queryRunner.query(`ALTER TABLE "app_finance_transactions" DROP CONSTRAINT "FK_app_finance_transactions_subscription"`);
        await queryRunner.query(`ALTER TABLE "app_agent_keys" DROP CONSTRAINT "FK_agent_keys_account"`);
        await queryRunner.query(`ALTER TABLE "app_chat_conversation" DROP CONSTRAINT "FK_chat_conversation_account"`);
        await queryRunner.query(`ALTER TABLE "app_chat_message" DROP CONSTRAINT "FK_chat_message_conversation"`);
        await queryRunner.query(`ALTER TABLE "app_chat_message" DROP CONSTRAINT "FK_chat_message_account"`);
        await queryRunner.query(`ALTER TABLE "app_chat_message" DROP CONSTRAINT "FK_chat_message_agent_key"`);
        await queryRunner.query(`ALTER TABLE "app_chat_message" DROP CONSTRAINT "FK_chat_message_reply"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_stream_streamed_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_app_habit_entry_habit_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_app_habit_entry_account"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_habit_entry_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_habit_entry_habit"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_app_habit_account_name"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_app_finance_wallets_account"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_app_finance_wallets_external"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_app_finance_categories_account"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_app_finance_categories_external"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_app_finance_subscriptions_account"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_app_finance_transactions_account_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_app_finance_transactions_external"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_transaction_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_transaction_wallet"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_transaction_category"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_agent_keys_account_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_agent_keys_prefix"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_agent_keys_prefix_active"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_chat_message_conversation"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_chat_message_account_status"`);
        await queryRunner.query(`CREATE TABLE "app_media_item" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "accountId" uuid NOT NULL, "title" character varying(500) NOT NULL, "type" character varying(10) NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'planning', "rating" numeric(3,1), "startDate" date, "endDate" date, "notes" text, "coverUrl" character varying(1000), "metadata" jsonb NOT NULL DEFAULT '{}', "externalIds" jsonb NOT NULL DEFAULT '{}', CONSTRAINT "PK_e4ac67669e47e7e52d5c8807898" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6ce3b30872eea8504f161f92e2" ON "app_media_item" ("accountId", "title", "type") `);
        await queryRunner.query(`CREATE INDEX "IDX_77ff4f0f827afc60b5b7dd988b" ON "app_media_item" ("accountId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_d095271eedf3f15f3f60e3ffa5" ON "app_media_item" ("accountId", "type") `);
        await queryRunner.query(`CREATE TABLE "app_finance_budgets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "accountId" uuid NOT NULL, "amount" numeric(12,2) NOT NULL, "period" character varying(20) NOT NULL DEFAULT 'monthly', "categoryId" uuid, CONSTRAINT "PK_e1ed08be02050700945ccb780e8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5fbafde5adc5066e8be0ef01eb" ON "app_finance_budgets" ("accountId", "categoryId", "period") `);
        await queryRunner.query(`ALTER TABLE "app_account_preferences" ADD "dashboardWidgets" jsonb`);
        await queryRunner.query(`ALTER TYPE "public"."app_theme_mode" RENAME TO "app_theme_mode_old"`);
        await queryRunner.query(`CREATE TYPE "public"."app_account_preferences_thememode_enum" AS ENUM('dark', 'light', 'auto')`);
        await queryRunner.query(`ALTER TABLE "app_account_preferences" ALTER COLUMN "themeMode" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "app_account_preferences" ALTER COLUMN "themeMode" TYPE "public"."app_account_preferences_thememode_enum" USING "themeMode"::"text"::"public"."app_account_preferences_thememode_enum"`);
        await queryRunner.query(`ALTER TABLE "app_account_preferences" ALTER COLUMN "themeMode" SET DEFAULT 'dark'`);
        await queryRunner.query(`DROP TYPE "public"."app_theme_mode_old"`);
        await queryRunner.query(`ALTER TYPE "public"."app_sidebar_position" RENAME TO "app_sidebar_position_old"`);
        await queryRunner.query(`CREATE TYPE "public"."app_account_preferences_sidebarposition_enum" AS ENUM('left', 'right')`);
        await queryRunner.query(`ALTER TABLE "app_account_preferences" ALTER COLUMN "sidebarPosition" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "app_account_preferences" ALTER COLUMN "sidebarPosition" TYPE "public"."app_account_preferences_sidebarposition_enum" USING "sidebarPosition"::"text"::"public"."app_account_preferences_sidebarposition_enum"`);
        await queryRunner.query(`ALTER TABLE "app_account_preferences" ALTER COLUMN "sidebarPosition" SET DEFAULT 'left'`);
        await queryRunner.query(`DROP TYPE "public"."app_sidebar_position_old"`);
        await queryRunner.query(`ALTER TYPE "public"."app_density" RENAME TO "app_density_old"`);
        await queryRunner.query(`CREATE TYPE "public"."app_account_preferences_density_enum" AS ENUM('compact', 'comfortable', 'spacious')`);
        await queryRunner.query(`ALTER TABLE "app_account_preferences" ALTER COLUMN "density" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "app_account_preferences" ALTER COLUMN "density" TYPE "public"."app_account_preferences_density_enum" USING "density"::"text"::"public"."app_account_preferences_density_enum"`);
        await queryRunner.query(`ALTER TABLE "app_account_preferences" ALTER COLUMN "density" SET DEFAULT 'comfortable'`);
        await queryRunner.query(`DROP TYPE "public"."app_density_old"`);
        await queryRunner.query(`ALTER TABLE "app_habit_entry" ALTER COLUMN "numericValue" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "app_habit" ALTER COLUMN "iconName" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "app_habit" ALTER COLUMN "trackingType" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "app_habit" ALTER COLUMN "frequencyType" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "app_habit" ALTER COLUMN "frequencyTarget" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "app_habit" ALTER COLUMN "numericPassThreshold" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "app_habit" ALTER COLUMN "numericSkipThreshold" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "app_habit" ALTER COLUMN "numericUnit" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "app_finance_transactions" DROP COLUMN "linkedTransferId"`);
        await queryRunner.query(`ALTER TABLE "app_finance_transactions" ADD "linkedTransferId" character varying`);
        await queryRunner.query(`ALTER TABLE "app_agent_keys" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "app_agent_keys" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "app_agent_keys" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "app_agent_keys" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_bcc2b7056625cc359dfb2f5148" ON "app_habit_entry" ("habitId", "date") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_143cdc9e49b7be0b22afa83dee" ON "app_habit" ("accountId", "name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_504edb9616ee8edbf97995a288" ON "app_finance_wallets" ("accountId", "externalId") WHERE "externalId" IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_578fb2fc6fd65bb1063b10fc25" ON "app_finance_categories" ("accountId", "externalId") WHERE "externalId" IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5554a6a8cd6b27f135873ccb11" ON "app_finance_transactions" ("accountId", "externalId") WHERE "externalId" IS NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_a0b8de3ebc1a02312440ca975c" ON "app_finance_transactions" ("accountId", "transactionDate") `);
        await queryRunner.query(`ALTER TABLE "app_account_preferences" ADD CONSTRAINT "FK_fecca8e97d0ce7d0509a78e9b84" FOREIGN KEY ("accountId") REFERENCES "app_account"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "app_media_item" ADD CONSTRAINT "FK_71353e31926d2efbb7613642cb3" FOREIGN KEY ("accountId") REFERENCES "app_account"("id") ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE "app_habit_entry" ADD CONSTRAINT "FK_2614f738fa523fa8418848138ba" FOREIGN KEY ("accountId") REFERENCES "app_account"("id") ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE "app_habit_entry" ADD CONSTRAINT "FK_ed0119353a370713644d496d92a" FOREIGN KEY ("habitId") REFERENCES "app_habit"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "app_habit" ADD CONSTRAINT "FK_4c355680e26faa2be1b638813d1" FOREIGN KEY ("accountId") REFERENCES "app_account"("id") ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE "app_finance_wallets" ADD CONSTRAINT "FK_34802626c390ca4202db458a474" FOREIGN KEY ("accountId") REFERENCES "app_account"("id") ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE "app_finance_categories" ADD CONSTRAINT "FK_0e2c6805d96f90b4bdfcead6a08" FOREIGN KEY ("accountId") REFERENCES "app_account"("id") ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE "app_finance_categories" ADD CONSTRAINT "FK_50cc3f512a8391c0717ff6b7eb2" FOREIGN KEY ("parentCategoryId") REFERENCES "app_finance_categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "app_finance_subscriptions" ADD CONSTRAINT "FK_40652d86a51a1b3983f6bddad53" FOREIGN KEY ("accountId") REFERENCES "app_account"("id") ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE "app_finance_subscriptions" ADD CONSTRAINT "FK_87b45a5ddda3b6aa6d69b1c6c21" FOREIGN KEY ("walletId") REFERENCES "app_finance_wallets"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "app_finance_subscriptions" ADD CONSTRAINT "FK_01b88f956fdb3132b15a81f8493" FOREIGN KEY ("categoryId") REFERENCES "app_finance_categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "app_finance_transactions" ADD CONSTRAINT "FK_a5304c82c42f90c99b829fd0be5" FOREIGN KEY ("accountId") REFERENCES "app_account"("id") ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE "app_finance_transactions" ADD CONSTRAINT "FK_f797d88de5e73f8cfd46a2ff042" FOREIGN KEY ("categoryId") REFERENCES "app_finance_categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "app_finance_transactions" ADD CONSTRAINT "FK_9fdb375e4830d43a3e9221cfe77" FOREIGN KEY ("walletId") REFERENCES "app_finance_wallets"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "app_finance_transactions" ADD CONSTRAINT "FK_e82cdbf2d61a1a1d33ea22e98fb" FOREIGN KEY ("subscriptionId") REFERENCES "app_finance_subscriptions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "app_finance_budgets" ADD CONSTRAINT "FK_6fb8358056e7de5c3d242cccde0" FOREIGN KEY ("accountId") REFERENCES "app_account"("id") ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE "app_finance_budgets" ADD CONSTRAINT "FK_9cddd118e0af2b443ba5ade65b8" FOREIGN KEY ("categoryId") REFERENCES "app_finance_categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "app_agent_keys" ADD CONSTRAINT "FK_319573c92adae1439d42e702911" FOREIGN KEY ("accountId") REFERENCES "app_account"("id") ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE "app_chat_conversation" ADD CONSTRAINT "FK_83f7c1cb38dcdf79763e329f40e" FOREIGN KEY ("accountId") REFERENCES "app_account"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "app_chat_message" ADD CONSTRAINT "FK_f1f924e82bbcfe6807a0203f475" FOREIGN KEY ("conversationId") REFERENCES "app_chat_conversation"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "app_chat_message" ADD CONSTRAINT "FK_ec9c5ebdbe6ee2bf93ad75ecbe0" FOREIGN KEY ("accountId") REFERENCES "app_account"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "app_chat_message" ADD CONSTRAINT "FK_fbbd2f947ed225c279ae1672ebf" FOREIGN KEY ("agentKeyId") REFERENCES "app_agent_keys"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "app_chat_message" ADD CONSTRAINT "FK_7eea09c81f89f5fb6b27c4f7682" FOREIGN KEY ("replyToId") REFERENCES "app_chat_message"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "app_chat_message" DROP CONSTRAINT "FK_7eea09c81f89f5fb6b27c4f7682"`);
        await queryRunner.query(`ALTER TABLE "app_chat_message" DROP CONSTRAINT "FK_fbbd2f947ed225c279ae1672ebf"`);
        await queryRunner.query(`ALTER TABLE "app_chat_message" DROP CONSTRAINT "FK_ec9c5ebdbe6ee2bf93ad75ecbe0"`);
        await queryRunner.query(`ALTER TABLE "app_chat_message" DROP CONSTRAINT "FK_f1f924e82bbcfe6807a0203f475"`);
        await queryRunner.query(`ALTER TABLE "app_chat_conversation" DROP CONSTRAINT "FK_83f7c1cb38dcdf79763e329f40e"`);
        await queryRunner.query(`ALTER TABLE "app_agent_keys" DROP CONSTRAINT "FK_319573c92adae1439d42e702911"`);
        await queryRunner.query(`ALTER TABLE "app_finance_budgets" DROP CONSTRAINT "FK_9cddd118e0af2b443ba5ade65b8"`);
        await queryRunner.query(`ALTER TABLE "app_finance_budgets" DROP CONSTRAINT "FK_6fb8358056e7de5c3d242cccde0"`);
        await queryRunner.query(`ALTER TABLE "app_finance_transactions" DROP CONSTRAINT "FK_e82cdbf2d61a1a1d33ea22e98fb"`);
        await queryRunner.query(`ALTER TABLE "app_finance_transactions" DROP CONSTRAINT "FK_9fdb375e4830d43a3e9221cfe77"`);
        await queryRunner.query(`ALTER TABLE "app_finance_transactions" DROP CONSTRAINT "FK_f797d88de5e73f8cfd46a2ff042"`);
        await queryRunner.query(`ALTER TABLE "app_finance_transactions" DROP CONSTRAINT "FK_a5304c82c42f90c99b829fd0be5"`);
        await queryRunner.query(`ALTER TABLE "app_finance_subscriptions" DROP CONSTRAINT "FK_01b88f956fdb3132b15a81f8493"`);
        await queryRunner.query(`ALTER TABLE "app_finance_subscriptions" DROP CONSTRAINT "FK_87b45a5ddda3b6aa6d69b1c6c21"`);
        await queryRunner.query(`ALTER TABLE "app_finance_subscriptions" DROP CONSTRAINT "FK_40652d86a51a1b3983f6bddad53"`);
        await queryRunner.query(`ALTER TABLE "app_finance_categories" DROP CONSTRAINT "FK_50cc3f512a8391c0717ff6b7eb2"`);
        await queryRunner.query(`ALTER TABLE "app_finance_categories" DROP CONSTRAINT "FK_0e2c6805d96f90b4bdfcead6a08"`);
        await queryRunner.query(`ALTER TABLE "app_finance_wallets" DROP CONSTRAINT "FK_34802626c390ca4202db458a474"`);
        await queryRunner.query(`ALTER TABLE "app_habit" DROP CONSTRAINT "FK_4c355680e26faa2be1b638813d1"`);
        await queryRunner.query(`ALTER TABLE "app_habit_entry" DROP CONSTRAINT "FK_ed0119353a370713644d496d92a"`);
        await queryRunner.query(`ALTER TABLE "app_habit_entry" DROP CONSTRAINT "FK_2614f738fa523fa8418848138ba"`);
        await queryRunner.query(`ALTER TABLE "app_media_item" DROP CONSTRAINT "FK_71353e31926d2efbb7613642cb3"`);
        await queryRunner.query(`ALTER TABLE "app_account_preferences" DROP CONSTRAINT "FK_fecca8e97d0ce7d0509a78e9b84"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a0b8de3ebc1a02312440ca975c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5554a6a8cd6b27f135873ccb11"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_578fb2fc6fd65bb1063b10fc25"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_504edb9616ee8edbf97995a288"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_143cdc9e49b7be0b22afa83dee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bcc2b7056625cc359dfb2f5148"`);
        await queryRunner.query(`ALTER TABLE "app_agent_keys" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "app_agent_keys" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "app_agent_keys" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "app_agent_keys" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "app_finance_transactions" DROP COLUMN "linkedTransferId"`);
        await queryRunner.query(`ALTER TABLE "app_finance_transactions" ADD "linkedTransferId" uuid`);
        await queryRunner.query(`ALTER TABLE "app_habit" ALTER COLUMN "numericUnit" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "app_habit" ALTER COLUMN "numericSkipThreshold" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "app_habit" ALTER COLUMN "numericPassThreshold" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "app_habit" ALTER COLUMN "frequencyTarget" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "app_habit" ALTER COLUMN "frequencyType" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "app_habit" ALTER COLUMN "trackingType" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "app_habit" ALTER COLUMN "iconName" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "app_habit_entry" ALTER COLUMN "numericValue" SET DEFAULT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."app_density_old" AS ENUM('compact', 'comfortable', 'spacious')`);
        await queryRunner.query(`ALTER TABLE "app_account_preferences" ALTER COLUMN "density" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "app_account_preferences" ALTER COLUMN "density" TYPE "public"."app_density_old" USING "density"::"text"::"public"."app_density_old"`);
        await queryRunner.query(`ALTER TABLE "app_account_preferences" ALTER COLUMN "density" SET DEFAULT 'comfortable'`);
        await queryRunner.query(`DROP TYPE "public"."app_account_preferences_density_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."app_density_old" RENAME TO "app_density"`);
        await queryRunner.query(`CREATE TYPE "public"."app_sidebar_position_old" AS ENUM('left', 'right')`);
        await queryRunner.query(`ALTER TABLE "app_account_preferences" ALTER COLUMN "sidebarPosition" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "app_account_preferences" ALTER COLUMN "sidebarPosition" TYPE "public"."app_sidebar_position_old" USING "sidebarPosition"::"text"::"public"."app_sidebar_position_old"`);
        await queryRunner.query(`ALTER TABLE "app_account_preferences" ALTER COLUMN "sidebarPosition" SET DEFAULT 'left'`);
        await queryRunner.query(`DROP TYPE "public"."app_account_preferences_sidebarposition_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."app_sidebar_position_old" RENAME TO "app_sidebar_position"`);
        await queryRunner.query(`CREATE TYPE "public"."app_theme_mode_old" AS ENUM('dark', 'light', 'auto')`);
        await queryRunner.query(`ALTER TABLE "app_account_preferences" ALTER COLUMN "themeMode" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "app_account_preferences" ALTER COLUMN "themeMode" TYPE "public"."app_theme_mode_old" USING "themeMode"::"text"::"public"."app_theme_mode_old"`);
        await queryRunner.query(`ALTER TABLE "app_account_preferences" ALTER COLUMN "themeMode" SET DEFAULT 'dark'`);
        await queryRunner.query(`DROP TYPE "public"."app_account_preferences_thememode_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."app_theme_mode_old" RENAME TO "app_theme_mode"`);
        await queryRunner.query(`ALTER TABLE "app_account_preferences" DROP COLUMN "dashboardWidgets"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5fbafde5adc5066e8be0ef01eb"`);
        await queryRunner.query(`DROP TABLE "app_finance_budgets"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d095271eedf3f15f3f60e3ffa5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77ff4f0f827afc60b5b7dd988b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ce3b30872eea8504f161f92e2"`);
        await queryRunner.query(`DROP TABLE "app_media_item"`);
        await queryRunner.query(`CREATE INDEX "IDX_chat_message_account_status" ON "app_chat_message" ("accountId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_chat_message_conversation" ON "app_chat_message" ("conversationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_agent_keys_prefix_active" ON "app_agent_keys" ("isActive", "keyPrefix") `);
        await queryRunner.query(`CREATE INDEX "IDX_agent_keys_prefix" ON "app_agent_keys" ("keyPrefix") `);
        await queryRunner.query(`CREATE INDEX "IDX_agent_keys_account_id" ON "app_agent_keys" ("accountId") `);
        await queryRunner.query(`CREATE INDEX "IDX_transaction_category" ON "app_finance_transactions" ("categoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_transaction_wallet" ON "app_finance_transactions" ("walletId") `);
        await queryRunner.query(`CREATE INDEX "IDX_transaction_date" ON "app_finance_transactions" ("transactionDate") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_app_finance_transactions_external" ON "app_finance_transactions" ("accountId", "externalId") WHERE ("externalId" IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_app_finance_transactions_account_date" ON "app_finance_transactions" ("accountId", "transactionDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_app_finance_subscriptions_account" ON "app_finance_subscriptions" ("accountId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_app_finance_categories_external" ON "app_finance_categories" ("accountId", "externalId") WHERE ("externalId" IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_app_finance_categories_account" ON "app_finance_categories" ("accountId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_app_finance_wallets_external" ON "app_finance_wallets" ("accountId", "externalId") WHERE ("externalId" IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_app_finance_wallets_account" ON "app_finance_wallets" ("accountId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_app_habit_account_name" ON "app_habit" ("accountId", "name") `);
        await queryRunner.query(`CREATE INDEX "IDX_habit_entry_habit" ON "app_habit_entry" ("habitId") `);
        await queryRunner.query(`CREATE INDEX "IDX_habit_entry_date" ON "app_habit_entry" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_app_habit_entry_account" ON "app_habit_entry" ("accountId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_app_habit_entry_habit_date" ON "app_habit_entry" ("date", "habitId") `);
        await queryRunner.query(`CREATE INDEX "IDX_stream_streamed_at" ON "app_stream" ("streamedAt") `);
        await queryRunner.query(`ALTER TABLE "app_chat_message" ADD CONSTRAINT "FK_chat_message_reply" FOREIGN KEY ("replyToId") REFERENCES "app_chat_message"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "app_chat_message" ADD CONSTRAINT "FK_chat_message_agent_key" FOREIGN KEY ("agentKeyId") REFERENCES "app_agent_keys"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "app_chat_message" ADD CONSTRAINT "FK_chat_message_account" FOREIGN KEY ("accountId") REFERENCES "app_account"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "app_chat_message" ADD CONSTRAINT "FK_chat_message_conversation" FOREIGN KEY ("conversationId") REFERENCES "app_chat_conversation"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "app_chat_conversation" ADD CONSTRAINT "FK_chat_conversation_account" FOREIGN KEY ("accountId") REFERENCES "app_account"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "app_agent_keys" ADD CONSTRAINT "FK_agent_keys_account" FOREIGN KEY ("accountId") REFERENCES "app_account"("id") ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE "app_finance_transactions" ADD CONSTRAINT "FK_app_finance_transactions_subscription" FOREIGN KEY ("subscriptionId") REFERENCES "app_finance_subscriptions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "app_finance_transactions" ADD CONSTRAINT "FK_app_finance_transactions_wallet" FOREIGN KEY ("walletId") REFERENCES "app_finance_wallets"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "app_finance_transactions" ADD CONSTRAINT "FK_app_finance_transactions_category" FOREIGN KEY ("categoryId") REFERENCES "app_finance_categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "app_finance_transactions" ADD CONSTRAINT "FK_app_finance_transactions_account" FOREIGN KEY ("accountId") REFERENCES "app_account"("id") ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE "app_finance_subscriptions" ADD CONSTRAINT "FK_app_finance_subscriptions_category" FOREIGN KEY ("categoryId") REFERENCES "app_finance_categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "app_finance_subscriptions" ADD CONSTRAINT "FK_app_finance_subscriptions_wallet" FOREIGN KEY ("walletId") REFERENCES "app_finance_wallets"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "app_finance_subscriptions" ADD CONSTRAINT "FK_app_finance_subscriptions_account" FOREIGN KEY ("accountId") REFERENCES "app_account"("id") ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE "app_finance_categories" ADD CONSTRAINT "FK_app_finance_categories_parent" FOREIGN KEY ("parentCategoryId") REFERENCES "app_finance_categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "app_finance_categories" ADD CONSTRAINT "FK_app_finance_categories_account" FOREIGN KEY ("accountId") REFERENCES "app_account"("id") ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE "app_finance_wallets" ADD CONSTRAINT "FK_app_finance_wallets_account" FOREIGN KEY ("accountId") REFERENCES "app_account"("id") ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE "app_habit" ADD CONSTRAINT "FK_app_habit_account" FOREIGN KEY ("accountId") REFERENCES "app_account"("id") ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE "app_habit_entry" ADD CONSTRAINT "FK_app_habit_entry_habit" FOREIGN KEY ("habitId") REFERENCES "app_habit"("id") ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE "app_habit_entry" ADD CONSTRAINT "FK_app_habit_entry_account" FOREIGN KEY ("accountId") REFERENCES "app_account"("id") ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE "app_account_preferences" ADD CONSTRAINT "FK_account_preferences_account" FOREIGN KEY ("accountId") REFERENCES "app_account"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
